export const FETCH_SHOWS_START = 'FETCH_SHOWS_START'
export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS'
export const FETCH_SHOWS_ERROR = 'FETCH_SHOWS_ERROR'
export const FETCH_SHOW_SUCCESS = 'FETCH_SHOW_SUCCESS'
export const FETCH_SEASONS_SUCCESS = 'FETCH_SEASONS_SUCCESS'
export const FETCH_EPISODES_SUCCESS = 'FETCH_EPISODES_SUCCESS'
export const CLEAR_SHOWS = 'CLEAR_SHOWS'


export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR'

export const FETCH_USER_START = 'FETCH_USER_START'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const ADD_SHOW_SUCCESS = 'ADD_SHOW_SUCCESS'
export const IS_SHOW_IN_LIST = 'IS_SHOW_IN_LIST'
