export const FETCH_SHOWS_START = 'FETCH_SHOWS_START'
export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS'
export const FETCH_SHOWS_ERROR = 'FETCH_SHOWS_ERROR'
export const FETCH_SHOW_SUCCESS = 'FETCH_SHOW_SUCCESS'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'